pub const FIRST_WORD_AWNSER: [[&str; 26]; 5] = [
    [
        "aitres", "baiser", "caries", "desira", "etires", "furies", "garnie", "haires", "inouie",
        "juntes", "kinase", "liures", "maries", "noires", "orties", "paries", "quetas", "retais",
        "saurie", "taries", "usante", "varies", "waters", "xenope", "yourte", "zonais",
    ],
    [
        "alaires", "bruites", "cariste", "detires", "enraies", "fruites", "garnies", "hatiers",
        "inuites", "jouites", "karites", "latines", "marines", "natures", "otaries", "parties",
        "quintes", "retiras", "sauries", "tarites", "urinees", "virales", "weblogs", "xenisme",
        "yourtes", "zonates",
    ],
    [
        "artisane", "brunites", "cortines", "dunaires", "encartes", "fruitees", "granites",
        "haleines", "incuries", "jaunites", "kainites", "latrines", "marinees", "notaires",
        "oralites", "partions", "quantite", "reniates", "saurites", "tartines", "ulnaires",
        "varietes", "wormiens", "xanthies", "yproises", "zerotais",
    ],
    [
        "autorisee",
        "barulions",
        "coltinees",
        "decintras",
        "entamures",
        "feutrines",
        "granitees",
        "hersaient",
        "insaturee",
        "jantieres",
        "keratines",
        "latinisee",
        "maronites",
        "notariees",
        "ouatinees",
        "proteines",
        "quetaines",
        "raturions",
        "soutirees",
        "triturons",
        "uranistes",
        "variolees",
        "webmaster",
        "xanthines",
        "yeomanrys",
        "zieutames",
    ],
    [
        "autoneiges",
        "brutalisee",
        "contraires",
        "decatirons",
        "enucleates",
        "flirteuses",
        "granulites",
        "harmonisee",
        "intercales",
        "juratoires",
        "kaolinites",
        "latinisees",
        "monetaires",
        "notariales",
        "orientales",
        "partirions",
        "quantiemes",
        "repaitrons",
        "surtoilees",
        "triturions",
        "uraninites",
        "virulentes",
        "wagneriens",
        "xerocopies",
        "youtserent",
        "zieuterons",
    ],
];
